// This file is part of Gear.

// Copyright (C) 2022 Gear Technologies Inc.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_gear_program
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
<<<<<<< HEAD
//! DATE: 2022-09-17, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `epyc-runners-node.hetzner`, CPU: `AMD EPYC 7502P 32-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("vara-dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/gear benchmark pallet --chain=vara-dev --steps=50 --repeat=20 --pallet=pallet_gear_program --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./scripts/benchmarking/weights-output/pallet_gear_program.rs --template=.maintain/frame-weight-template.hbs
=======
//! DATE: 2022-09-07, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("vara-dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/gear-node benchmark pallet --chain=vara-dev --steps=50 --repeat=20 --pallet=pallet_gear_program --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --output=./scripts/benchmarking/weights-output/pallet_gear_program.rs --template=.maintain/frame-weight-template.hbs
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_gear_program.
pub trait WeightInfo {
    fn resume_program(q: u32, ) -> Weight;
}

/// Weights for pallet_gear_program using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_gear_program::WeightInfo for SubstrateWeight<T> {
<<<<<<< HEAD
    /// The range of component `q` is `[1, 128]`.
    fn resume_program(q: u32, ) -> Weight {
        Weight::from_ref_time(349_268_000 as u64)
            // Standard Error: 417_738
            .saturating_add(Weight::from_ref_time(199_197_378 as u64).saturating_mul(q as u64))
            .saturating_add(T::DbWeight::get().reads(4 as u64))
            .saturating_add(T::DbWeight::get().writes(22 as u64))
            .saturating_add(T::DbWeight::get().writes((16 as u64).saturating_mul(q as u64)))
=======
    fn resume_program(q: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 478_000
            .saturating_add((201_308_000 as Weight).saturating_mul(q as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(6 as Weight))
            .saturating_add(T::DbWeight::get().writes((16 as Weight).saturating_mul(q as Weight)))
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
<<<<<<< HEAD
    /// The range of component `q` is `[1, 128]`.
    fn resume_program(q: u32, ) -> Weight {
        Weight::from_ref_time(349_268_000 as u64)
            // Standard Error: 417_738
            .saturating_add(Weight::from_ref_time(199_197_378 as u64).saturating_mul(q as u64))
            .saturating_add(RocksDbWeight::get().reads(4 as u64))
            .saturating_add(RocksDbWeight::get().writes(22 as u64))
            .saturating_add(RocksDbWeight::get().writes((16 as u64).saturating_mul(q as u64)))
    }
}
=======
    fn resume_program(q: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 478_000
            .saturating_add((201_308_000 as Weight).saturating_mul(q as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(6 as Weight))
            .saturating_add(RocksDbWeight::get().writes((16 as Weight).saturating_mul(q as Weight)))
    }
}
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
